name: CI
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: ${{secrets.PROJECT_KEY}}
       FLOW_API_URL: ${{secrets.HOMOLOGA_URL}}
       PASSWORD: "TESTEEE12356"
   steps:
   - uses: actions/checkout@v2

   - name: Run SAST
     run: conviso sast run
